--- # Routes. Please read comments in root (-/:) for how to write new routes

-/: # the name of the route URI.
    #Only explicitly declared routes are accessible to the server.
    [ all ] # list of methods that may be called on the route.
    # [ all ] (by itself) or any of [ get, head, post, put, delete, option ]

-/file1: [ get, head, option ]

-/coffee: [ get, head, option ]