---

/:
  allowed-methods: GET
  redirect-uri: ""
  authorization: ""

/exampleRoute1:
  allowed-methods: GET HEAD OPTIONS
  redirect-uri: ""
  authorization: ""

/exampleRoute2:
  allowed-methods: POST PUT
  redirect-uri: ""
  authorization: ""